### ISSUE TITLE
nodeHandle?nodeHandle:nodeHandle.getHostNode()

### ISSUE THREAD

**Issue by Amurmurmur** [infinitered/ignite-ir-boilerplate#137]
When running `yarn run test`
The following exception gets thrown:

```
 RUNS  Tests/StoriesTest.js
IgniteBoilerplate/node_modules/react-native/Libraries/Renderer/ReactNativeStack-dev.js:2324
return null==nodeHandle||"number"==typeof nodeHandle?nodeHandle:nodeHandle.getHostNode();
                                                                           ^

TypeError: nodeHandle.getHostNode is not a function
    at findNumericNodeHandleStack (IgniteBoilerplate/node_modules/react-native/Libraries/Renderer/ReactNativeStack-dev.js:2324:76)
    at Component.focus (IgniteBoilerplate/node_modules/react-native/Libraries/Renderer/ReactNativeStack-dev.js:2553:31)
    at Component.<anonymous> (IgniteBoilerplate/node_modules/react-timer-mixin/TimerMixin.js:18:16)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
error Command failed with exit code 1.
```
Thats for the fresh ignite project setup that I did by running:
```
ignite new IgniteBoilerplate
```

ignite doctor output:
```
System
  platform           darwin
  arch               x64
  cpu                4 cores                                                            Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
  directory          /Documents/IgniteBoilerplate

JavaScript
  node               8.4.0        /usr/local/bin/node
  npm                5.3.0        /usr/local/bin/npm
  yarn               0.27.5       /usr/local/bin/yarn

React Native
  react-native-cli   2.0.1
  app rn version     0.47.2

Ignite
  ignite             2.0.0        /usr/local/bin/ignite

Android
  java               1.8.0_92     /usr/bin/java
  android home       -            /Documents/AndroidSDK

iOS
  xcode              8.3.3
```

**Comment by Cengkaruk** [comment]
@Amurmurmur Any updates related to this issue?

**Comment by Amurmurmur** [comment]
@Cengkaruk I just dont run tests for now. It might have to do with `enzyme` not supporting latest react-native builds.
In one of the commits Infinite Red team removed githooks that run tests for now here: https://github.com/infinitered/ignite-ir-boilerplate/commit/be75af94abd91213a1abe31f7f773dc7fb80ae4c

**Comment by Cengkaruk** [comment]
@Amurmurmur Okay, thanks for your information.

**Comment by ruddell** [comment]
I'm pretty sure this was failing due to the `autofocus` attribute on the SearchBar.  Since that was removed in 540e6cc9c11138272c734795a1b2dbd15f1e09a4, you (hopefully) shouldn't run into this anymore once there's a new release.

I worked around it in an existing project by removing the `autofocus` attribute.

**Comment by jbosse** [comment]
@Cengkaruk is seems that @ruddell is correct that removing line 23 `autoFocus` `/App/Components/SearchBar.js` and lines 399 `autoCorrect={true}`and 522 `autoCorrect={false}` from `/Tests/__snapshots__/StoriesTest.js.snap` will result a green test run.
